FROM postgres:9.6-alpine

ADD postgresql/init-db.sh /docker-entrypoint-initdb.d/


ENV POSTGRES_USER=bookcrossing
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=bookcrossing
ENV PG_DATA=/var/lib/postgresql/data
