FROM python:3.6.3-slim

RUN mkdir -p /app/RecommenderSystem/recommendersystem
WORKDIR /app/RecommenderSystem/recommendersystem

ENV PYTHONPATH=/app

ADD requirements.txt .
ADD recommendersystem/ .

RUN pip3 install -r requirements.txt
CMD ["python", "-m", "unittest", "discover"]
