FROM postgres:9.6-alpine

ADD init.sql /docker-entrypoint-initdb.d/

ENV POSTGRES_USER=bookcrossing
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=bookcrossing
ENV PG_DATA=/var/lib/postgresql/data

ENV PGBOOKS=/data/BX-Books-Cleansed-Tini.csv
ENV PGUSERS=/data/BX-Users-Cleansed-Tini.csv
ENV PGRATINGS=/data/BX-Book-Ratings-Cleansed-Tini.csv
