---
- name: Create the target K8s namespace
  k8s:
    state: present
    definition: "{{ lookup('template', 'namespace.yml.j2') }}"

- name: Create the K8s secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'secret.yml.j2') }}"

- name: Create the K8s configmap
  k8s:
    state: present
    definition: "{{ lookup('template', 'configmap.yml.j2') }}"

- name: Create the K8s services
  k8s:
    state: present
    definition: "{{ lookup('template', 'service.yml.j2') }}"

- name: Create the K8s ingress
  k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.yml.j2') }}"

- name: Create the PostgreSQL database
  k8s:
    state: present
    definition: "{{ lookup('template', 'db-deployment.yml.j2') }}"

- name: Create the Recommender deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'app-deployment.yml.j2') }}"
