FROM python:3.6.3-slim

WORKDIR /usr/src/app

ADD requirements.txt .
RUN pip install -r requirements.txt

COPY . /usr/src/app

EXPOSE 8000

ENV DATABASE=postgres
ENV DATABASE_USER=bookcrossing
ENV DATABASE_PASSWORD=password
ENV DATABASE_HOST=postgres
ENV DATABASE_PORT=5432

CMD ./start_web.sh
