---
# tasks file for image_build
- name: Pull the postgresql image
  docker_image:
    name: postgres:9.6-alpine
    source: pull
  notify: clean images

- name: Stage the requirements file for the limited recommender image
  copy:
    src: ../requirements/requirements.txt
    dest: "{{ role_path }}/files"
  notify: unstage

- name: Stage the source code for the limited recommender image
  synchronize:
    src: ../recommendersystem/web
    dest: "{{ role_path }}/files"
  notify: unstage

- name: Build the limited recommender system image
  docker_image:
    name: limited_recommender
    source: build
    build:
      path: "{{ role_path }}/files"
      pull: yes
    force_source: yes
  notify: clean images

- name: Build the limited recommender system task image
  docker_image:
    name: limited_recommender_task
    source: build
    build:
      path: "{{ role_path }}/files"
      pull: no
      dockerfile: Dockerfile.task
    force_source: yes
  notify: clean images
