# Generated by Django 2.1.11 on 2019-09-19 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrossing', '0001_initial'),
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=14, max_digits=15)),
                ('rated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictive_item', to='bookcrossing.Book')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommended_item', to='bookcrossing.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='purchased',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
