# Generated by Django 2.1.11 on 2019-09-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20190919_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarity',
            old_name='rated',
            new_name='source',
        ),
    ]
