FROM python:3.6-alpine
WORKDIR /usr/src/app/
ENV PATH="/usr/src/app:${PATH}"

RUN apk update && apk add postgresql-dev gcc musl-dev nginx supervisor

ADD requirements.txt /
RUN pip install -r /requirements.txt

COPY start_web.sh /
COPY nginx.conf /etc/nginx/
COPY supervisor_web.conf /

COPY web .
CMD /start_web.sh
