on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A job to build
    steps:
      - uses: actions/checkout@v1
      - name: Display directory content
        run: ls -la
      - uses: ./.github/actions/build
