on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A job to build
    steps:
      - uses: actions/checkout@v1
      - name: Install build server pre-requirements
        run: sudo apt-get install python3-setuptools python3-dev
      - name: Install build requirements
        run: |
          pip3 list
          pip3 install -r requirements/build_requirements.txt
          pip3 list
          ansible --version
      - name: Run the installer to build the containers
        run: |
          cd installer/
          ansible --version
          ansible-playbook -i inventory install.yml
      #- uses: ./.github/actions/build
