on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A job to build
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: docker://cloud.docker.com/repository/docker/konkolorado/ansible:0.0.1
