on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A job to build
    steps:
      - uses: actions/checkout@v1
      - name: Install build server requirements
        run: |
          sudo apt-get install python3-setuptools
          pip3 install -r requirements/build_requirements.txt
      - name: Run the installer to build the containers
        run: |
          cd installer/
          ansible-playbook -i inventory install.yml -e \
            'ansible_python_interpreter=/usr/bin/python3
            build_image=true
            build_only=true'
      - name: Push the built images to DockerHub
        run: |
          docker images
          docker ps -a
      #- uses: ./.github/actions/build
