on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A job to build
    steps:
      - uses: actions/checkout@v1
      - name: Install ansible for building
        run: sudo apt-get install ansible -y
      - uses: ./.github/actions/build
