on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A job to build
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Display directory context
        run: pwd
      - name: Display directory content
        run: ls
      - uses: ./
