on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A job to build
    steps:
      - uses: actions/checkout@v1
      - name: Install build server pre-requirements
        run: sudo apt-get install python3-setuptools
      - name: Install build requirements
        run: pip3 install -r requirements/build_requirements.txt
      - name: Run the installer to build the containers
        run: |
          cd installer/
          ansible-playbook -i inventory install.yml -e \
            'ansible_python_interpreter=/usr/bin/python3
            build_image=true'
      #- uses: ./.github/actions/build
