# BUILD AND DEPLOYMENT VARIABLES
build_images: "true"

# Deployment method is either compose or kubernetes
# compose is for local development, kubernetes is for deployment
deploy_app: "false"
deployment: "compose"

# Namespace to deploy into when deploying into K8s
recommender_namespace: "recommender"

# ------------------------- #

# APPLICATION VARIABLES
database_name: "bookcrossing"
database_user: "bookcrossing"
database_host: "postgresql"
database_port: "5432"
database_password: "password"

rabbitmq_user: "recommender"
rabbitmq_vhost: "recommender"
rabbitmq_host: "rabbitmq"
rabbitmq_port: "5672"
rabbitmq_erlang_cookie: "cookiemonster"
rabbitmq_password: "password"

django_secret_key: "supersecretkey"
