---
- name: Build and deploy the limited recommender system
  hosts: all
  gather_facts: false
  force_handlers: true

  tasks:
    - include_role:
        name: image_build
      when: image_build == "True"
    - include_role:
        name: dev_deploy
      when: mode == "DEVELOPMENT"
    - include_role:
        name: prod_deploy
      when: mode == "PRODUCTION"
