---
- name: Build and deploy the limited recommender system
  hosts: all
  gather_facts: false
  force_handlers: true

  tasks:
    - include_vars:
        file: config.yml

    - include_role:
        name: image_build
      when: image_build == "True"

    - include_role:
        name: compose
      when: deployment == "compose"

    - include_role:
        name: kubernetes
      when: deployment == "kubernetes"
