---
- name: Build and deploy the limited recommender system
  hosts: all
  gather_facts: false
  force_handlers: true

  tasks:
    - include_vars:
        file: config.yml

    - include_role:
        name: image_build
      when: build_images | default(false) | bool

    - include_role:
        name: compose
      when:
        - deploy_app | default(false) | bool
        - deployment == "compose"

    - include_role:
        name: kubernetes
      when:
        - deploy_app | default(false) | bool
        - deployment == "kubernetes"
