---
- name: Build and deploy the limited recommender system
  hosts: all
  gather_facts: false
  force_handlers: true

  tasks:
    - include_role:
        name: image_build
      when: image_build == "True"

    - include_role:
        name: compose
      vars:
        deployment_env: "dev"
    #- include_tasks: dev_deploy.yml
    #  when: mode == "DEVELOPMENT"

    #- include_tasks: prod_deploy.yml
    #  when: mode == "PRODUCTION"
