---
- name: Build and deploy the limited recommender system
  hosts: all
  gather_facts: false
  force_handlers: true

  tasks:
    - include_vars:
        file: config.yml

    - include_role:
        name: image_build
      when: build_image|default(false)|bool

    - include_role:
        name: compose
      when:
        - deployment == "compose"
        - build_only == "false"

    - include_role:
        name: kubernetes
      when:
        - deployment == "kubernetes"
        - build_only == "false"
